version: "3.9"

services:
  db:
    image: postgres:15
    container_name: task15_db
    restart: always
    env_file:
      - .env.docker
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - app-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $${POSTGRES_USER} -d $${POSTGRES_DB}"]
      interval: 5s
      timeout: 5s
      retries: 5

  redis:
    image: redis:7-alpine
    restart: always
    ports:
      - "6379:6379"
    networks:
      - app-network

  app:
    build: .
    container_name: task15_app
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_started
    env_file:
      - .env.docker
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    networks:
      - app-network

  celery-worker:
    build: .
    container_name: task15_celery_worker
    command: celery -A app.celery_app worker --loglevel=info
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_started
    env_file:
      - .env.docker
    networks:
      - app-network

volumes:
  postgres_data:

networks:
  app-network:
