name: CI Pipeline

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build_and_test:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:15
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: Letsgo1234
          POSTGRES_DB: notes_db
        ports:
          - 5432:5432
        options: >-
          --health-cmd "pg_isready -U postgres -d notes_db"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

      redis:
        image: redis:7-alpine
        ports:
          - 6379:6379

    env:
      DATABASE_URL: postgresql+asyncpg://postgres:Letsgo1234@localhost:5432/notes_db
      REDIS_HOST: localhost
      REDIS_PORT: 6379
      SECRET_KEY: testsecretkey123
      ALGORITHM: HS256
      ACCESS_TOKEN_EXPIRE_MINUTES: 30
      PYTHONUNBUFFERED: 1

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pytest httpx

      - name: Run tests with pytest
        run: |
          pytest tests/

      - name: Build Docker image
        run: |
          docker build -t task15-app .